services:
  ssserver-rust:
    container_name: ssserver-rust
    image: ghcr.io/shadowsocks/ssserver-rust:latest
    restart: always
    network_mode: "host"
    volumes:
      - ./config.json:/etc/shadowsocks-rust/config.json

  shadow-tls:
    image: ghcr.io/ihciah/shadow-tls:latest
    restart: always
    network_mode: "host"
    environment:
      - MODE=server
      - LISTEN=0.0.0.0:8443
      - SERVER=127.0.0.1:24001
      - TLS=weather-data.apple.com:443
      - PASSWORD=CHANGE_ME
      - V3=true
      - STRICT=true
    depends_on:
      - ssserver-rust